name: CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: 'pudongpudong-backend'
  JAR_FILE_NAME: 'pudongpudong-backend-0.0.1-SNAPSHOT.jar'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.properties file from secret
        env:
          PROPERTIES_FILE: ${{ secrets.APPLICATION_PROPERTIES }}
        run: echo "${{ env.PROPERTIES_FILE }}" > src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-jar
          path: build/libs/${{ env.JAR_FILE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-jar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PROJECT_DIR=/home/ubuntu/${{ env.PROJECT_NAME }}
            JAR_NAME=${{ env.JAR_FILE_NAME }}

            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            sudo pkill -f $JAR_NAME

            mv $GITHUB_WORKSPACE/build-jar/$JAR_NAME .

            nohup java -jar $JAR_NAME > /dev/null 2>&1 &

            echo "Deployment finished."