name: CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

env:
  S3_BUCKET_NAME: 'pudongpudong-s3'
  PROJECT_NAME: 'pudongpudong-backend'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/${{ env.PROJECT_NAME }}
          git pull origin main
          ./gradlew build
          sudo pkill -f java
          nohup java -jar build/libs/${{ env.PROJECT_NAME }}-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &

    - name: health checking
      run: |
        sleep 60  # 애플리케이션이 시작될 때까지 60초 대기
        HEALTH_CHECK_URL="http://${{ secrets.EC2_IP }}:8080/actuator/health" # 헬스 체크 엔드포인트 URL
        
        while true; do
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_CHECK_URL)
          if [ "$RESPONSE" == "200" ]; then
            echo "Health check successful!"
            break
          else
            echo "Health check failed with status code $RESPONSE. Retrying..."
            sleep 10
          fi
        done
