name: CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_NAME: 'pudongpudong-backend'
  JAR_FILE_NAME: 'pudongpudong-backend.jar'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.properties file from secret
        run: |
          mkdir -p src/main/resources/
          cat > src/main/resources/application.properties << EOF
          ${{ secrets.APPLICATION_PROPERTIES }}
          EOF

      - name: Build with Gradle
        run: ./gradlew build

      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-jar
          path: build/libs/${{ env.JAR_FILE_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-jar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            PROJECT_DIR=/home/ubuntu/${{ env.PROJECT_NAME }}
            JAR_NAME=${{ env.JAR_FILE_NAME }}

            mkdir -p $PROJECT_DIR
            cd $PROJECT_DIR

            sudo pkill -f $JAR_NAME

            mv $GITHUB_WORKSPACE/$JAR_NAME .

            nohup java -jar $JAR_NAME > /dev/null 2>&1 &

      - name: health checking
        run: |
          sleep 60
          HEALTH_CHECK_URL="http://${{ secrets.EC2_IP }}:8080/actuator/health"
          
          while true; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_CHECK_URL)
            if [ "$RESPONSE" == "200" ]; then
              echo "Health check successful!"
              break
            else
              echo "Health check failed with status code $RESPONSE. Retrying in 10s..."
              sleep 10
            fi
          done